/** @file

Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this
  list of conditions and the following disclaimer in the documentation and/or
  other materials provided with the distribution.
* Neither the name of Intel Corporation nor the names of its contributors may
  be used to endorse or promote products derived from this software without
  specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
  THE POSSIBILITY OF SUCH DAMAGE.

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __FSPTUPD_H__
#define __FSPTUPD_H__

#include <FspUpd.h>

#pragma pack(1)


/** Fsp T Core UPD
**/
typedef struct {

/** Offset 0x0040
**/
  EFI_PHYSICAL_ADDRESS        MicrocodeRegionBase;

/** Offset 0x0048
**/
  UINT64                      MicrocodeRegionSize;

/** Offset 0x0050
**/
  EFI_PHYSICAL_ADDRESS        CodeRegionBase;

/** Offset 0x0058
**/
  UINT64                      CodeRegionSize;
} FSPT_CORE_UPD;

/** Fsp T Configuration
**/
typedef struct {

/** Offset 0x0060 - PcdLpssUartDebugEnable
  Enable SerialIo Uart debug library with/without initializing SerialIo Uart device in FSP.
  0:Disable, 1:Enable and Initialize, 2:Enable without Initializing
**/
  UINT8                       PcdLpssUartDebugEnable;

/** Offset 0x0061 - PcdLpssUartNumber
  Select SerialIo Uart Controller for debug. Note: If UART0 is selected as CNVi BT
  Core interface, it cannot be used for debug purpose.
  0:SerialIoUart0, 1:SerialIoUart1, 2:SerialIoUart2
**/
  UINT8                       PcdLpssUartNumber;

/** Offset 0x0062 - PcdLpssUartMode - FSPT
  Select SerialIo Uart Controller mode
  0:SerialIoUartDisabled, 1:SerialIoUartPci, 2:SerialIoUartHidden, 3:SerialIoUartCom,
  4:SerialIoUartSkipInit
**/
  UINT8                       PcdLpssUartMode;

/** Offset 0x0063 - PcdLpssUartPowerGating - FSPT
  Select SerialIo Uart Controller Powergating mode
  0:Disabled, 1:Enabled, 2:Auto
**/
  UINT8                       PcdLpssUartPowerGating;

/** Offset 0x0064 - PcdLpssUartBaudRate - FSPT
  Set default BaudRate Supported from 0 - default to 6000000
**/
  UINT32                      PcdLpssUartBaudRate;

/** Offset 0x0068 - Pci Express Base Address
  Base address to be programmed for Pci Express
**/
  UINT64                      PcdPciExpressBaseAddress;

/** Offset 0x0070 - Pci Express Region Length
  Region Length to be programmed for Pci Express
**/
  UINT32                      PcdPciExpressRegionLength;

/** Offset 0x0074 - PcdLpssUartParity - FSPT
  Set default Parity.
  0: DefaultParity, 1: NoParity, 2: EvenParity, 3: OddParity
**/
  UINT8                       PcdLpssUartParity;

/** Offset 0x0075 - PcdLpssUartDataBits - FSPT
  Set default word length. 0: Default, 5,6,7,8
**/
  UINT8                       PcdLpssUartDataBits;

/** Offset 0x0076 - PcdLpssUartStopBits - FSPT
  Set default stop bits.
  0: DefaultStopBits, 1: OneStopBit, 2: OneFiveStopBits, 3: TwoStopBits
**/
  UINT8                       PcdLpssUartStopBits;

/** Offset 0x0077 - PcdLpssUartAutoFlow - FSPT
  Enables UART hardware flow control, CTS and RTS lines.
  0: Disable, 1:Enable
**/
  UINT8                       PcdLpssUartAutoFlow;

/** Offset 0x0078 - PcdLpssUartRxPinMux - FSPT
  Select RX pin muxing for SerialIo UART used for debug
**/
  UINT32                      PcdLpssUartRxPinMux;

/** Offset 0x007C - PcdLpssUartTxPinMux - FSPT
  Select TX pin muxing for SerialIo UART used for debug
**/
  UINT32                      PcdLpssUartTxPinMux;

/** Offset 0x0080 - PcdLpssUartRtsPinMux - FSPT
  Select SerialIo Uart used for debug Rts pin muxing. Refer to GPIO_*_MUXING_SERIALIO_UARTx_RTS*
  for possible values.
**/
  UINT32                      PcdLpssUartRtsPinMux;

/** Offset 0x0084 - PcdLpssUartCtsPinMux - FSPT
  Select SerialIo Uart used for debug Cts pin muxing. Refer to GPIO_*_MUXING_SERIALIO_UARTx_CTS*
  for possible values.
**/
  UINT32                      PcdLpssUartCtsPinMux;

/** Offset 0x0088 - PcdLpssUartDebugMmioBase - FSPT
  Select SerialIo Uart default MMIO resource in SEC/PEI phase when PcdLpssUartMode
  = SerialIoUartPci.
**/
  UINT32                      PcdLpssUartDebugMmioBase;

/** Offset 0x008C - PcdLpssUartDebugPciCfgBase - FSPT
  Specify PciCfgBase address. Allows for SerialIO UART functionality outside Bus 0
**/
  UINT32                      PcdLpssUartDebugPciCfgBase;

/** Offset 0x0090 - PcdLpcUartDebugEnable
  Enable to initialize LPC Uart device in FSP.
  0:Disable, 1:Enable
**/
  UINT8                       PcdLpcUartDebugEnable;

/** Offset 0x0091 - Debug Interfaces
  Debug Interfaces. BIT0-RAM, BIT1-UART, BIT3-USB3, BIT4-Serial IO, BIT5-TraceHub,
  BIT2 - Not used.
**/
  UINT8                       PcdDebugInterfaceFlags;

/** Offset 0x0092 - PcdSerialDebugLevel
  Serial Debug Message Level. 0:Disable, 1:Error Only, 2:Error & Warnings, 3:Load,
  Error, Warnings & Info, 4:Load, Error, Warnings, Info & Event, 5:Load, Error, Warnings,
  Info & Verbose.
  0:Disable, 1:Error Only, 2:Error and Warnings, 3:Load Error Warnings and Info, 4:Load
  Error Warnings and Info, 5:Load Error Warnings Info and Verbose
**/
  UINT8                       PcdSerialDebugLevel;

/** Offset 0x0093 - ISA Serial Base selection
  Select ISA Serial Base address. Default is 0x3F8.
  0:0x3F8, 1:0x2F8
**/
  UINT8                       PcdIsaSerialUartBase;

/** Offset 0x0094 - PcdLpssUart2ndEnable
  Enable Additional SerialIo Uart device in FSP.
  0:Disable, 1:Enable and Initialize, 2:Enable without Initializing
**/
  UINT8                       PcdLpssUart2ndEnable;

/** Offset 0x0095 - PcdLpssUart2ndNumber
  Select SerialIo Uart Controller Number
  0:SerialIoUart0, 1:SerialIoUart1, 2:SerialIoUart2
**/
  UINT8                       PcdLpssUart2ndNumber;

/** Offset 0x0096 - PcdLpssUart2ndMode - FSPT
  Select SerialIo Uart Controller mode
  0:SerialIoUartDisabled, 1:SerialIoUartPci, 2:SerialIoUartHidden, 3:SerialIoUartCom,
  4:SerialIoUartSkipInit
**/
  UINT8                       PcdLpssUart2ndMode;

/** Offset 0x0097
**/
  UINT8                       FsptUpdRsvd196;

/** Offset 0x0098 - PcdLpssUart2ndBaudRate - FSPT
  Set default BaudRate Supported from 0 - default to 6000000
**/
  UINT32                      PcdLpssUart2ndBaudRate;

/** Offset 0x009C - PcdLpssUart2ndParity - FSPT
  Set default Parity.
  0: DefaultParity, 1: NoParity, 2: EvenParity, 3: OddParity
**/
  UINT8                       PcdLpssUart2ndParity;

/** Offset 0x009D - PcdLpssUart2ndDataBits - FSPT
  Set default word length. 0: Default, 5,6,7,8
**/
  UINT8                       PcdLpssUart2ndDataBits;

/** Offset 0x009E - PcdLpssUart2ndStopBits - FSPT
  Set default stop bits.
  0: DefaultStopBits, 1: OneStopBit, 2: OneFiveStopBits, 3: TwoStopBits
**/
  UINT8                       PcdLpssUart2ndStopBits;

/** Offset 0x009F - PcdLpssUart2ndAutoFlow - FSPT
  Enables UART hardware flow control, CTS and RTS lines.
  0: Disable, 1:Enable
**/
  UINT8                       PcdLpssUart2ndAutoFlow;

/** Offset 0x00A0 - PcdLpssUart2ndRxPinMux - FSPT
  Select RX pin muxing for SerialIo UART
**/
  UINT32                      PcdLpssUart2ndRxPinMux;

/** Offset 0x00A4 - PcdLpssUart2ndTxPinMux - FSPT
  Select TX pin muxing for SerialIo UART
**/
  UINT32                      PcdLpssUart2ndTxPinMux;

/** Offset 0x00A8 - PcdLpssUart2ndRtsPinMux - FSPT
  Select SerialIo Uart Rts pin muxing. Refer to GPIO_*_MUXING_SERIALIO_UARTx_RTS*
  for possible values.
**/
  UINT32                      PcdLpssUart2ndRtsPinMux;

/** Offset 0x00AC - PcdLpssUart2ndCtsPinMux - FSPT
  Select SerialIo Uart Cts pin muxing. Refer to GPIO_*_MUXING_SERIALIO_UARTx_CTS*
  for possible values.
**/
  UINT32                      PcdLpssUart2ndCtsPinMux;

/** Offset 0x00B0 - PcdLpssUart2ndMmioBase - FSPT
  Select SerialIo Uart default MMIO resource in SEC/PEI phase when PcdLpssUart2ndMode
  = SerialIoUartPci.
**/
  UINT32                      PcdLpssUart2ndMmioBase;

/** Offset 0x00B4 - PcdLpssUart2ndPciCfgBase - FSPT
  Specify PciCfgBase address. Allows for SerialIO UART functionality outside Bus 0
**/
  UINT32                      PcdLpssUart2ndPciCfgBase;

/** Offset 0x00B8
**/
  UINT32                      TopMemoryCacheSize;

/** Offset 0x00BC - Serial Io SPI Chip Select Polarity
  Sets polarity for each chip Select. Available options: 0:SerialIoSpiCsActiveLow,
  1:SerialIoSpiCsActiveHigh
**/
  UINT8                       PcdSerialIoSpiCsPolarity[2];

/** Offset 0x00BE - Serial Io SPI Chip Select Enable
  0:Disabled, 1:Enabled. Enables GPIO for CS0 or CS1 if it is Enabled
**/
  UINT8                       PcdSerialIoSpiCsEnable[2];

/** Offset 0x00C0 - Serial Io SPI Device Mode
  When mode is set to Pci, controller is initalized in early stage. Available modes:
  0:SerialIoSpiDisabled, 1:SerialIoSpiPci.
**/
  UINT8                       PcdSerialIoSpiMode;

/** Offset 0x00C1 - Serial Io SPI Default Chip Select Output
  Sets Default CS as Output. Available options: 0:CS0, 1:CS1
**/
  UINT8                       PcdSerialIoSpiDefaultCsOutput;

/** Offset 0x00C2 - Serial Io SPI Default Chip Select Mode HW/SW
  Sets Default CS Mode Hardware or Software. Available options: 0:HW, 1:SW
**/
  UINT8                       PcdSerialIoSpiCsMode;

/** Offset 0x00C3 - Serial Io SPI Default Chip Select State Low/High
  Sets Default CS State Low or High. Available options: 0:Low, 1:High
**/
  UINT8                       PcdSerialIoSpiCsState;

/** Offset 0x00C4 - Serial Io SPI Device Number
  Select which Serial Io SPI controller is initalized in early stage.
**/
  UINT8                       PcdSerialIoSpiNumber;

/** Offset 0x00C5
**/
  UINT8                       FsptUpdRsvd0[3];

/** Offset 0x00C8 - Serial Io SPI Device MMIO Base
  Assigns MMIO for Serial Io SPI controller usage in early stage.
**/
  UINT32                      PcdSerialIoSpiMmioBase;

/** Offset 0x00CC - Serial IO SPI CS Pin Muxing
  Select SerialIo SPI CS pin muxing. Refer to GPIO_*_MUXING_SERIALIO_SPIx_CS* for
  possible values.
**/
  UINT32                      PcdSerialIoSpiCsPinMux[2];

/** Offset 0x00D4 - Serial IO SPI CLK Pin Muxing
  Select SerialIo SPI CLK pin muxing. Refer to GPIO_*_MUXING_SERIALIO_SPIx_CLK* for
  possible values.
**/
  UINT32                      PcdSerialIoSpiClkPinMux;

/** Offset 0x00D8 - Serial IO SPI MISO Pin Muxing
  Select SerialIo SPI MISO pin muxing. Refer to GPIO_*_MUXING_SERIALIO_SPIx_MISO*
  for possible values.
**/
  UINT32                      PcdSerialIoSpiMisoPinMux;

/** Offset 0x00DC - Serial IO SPI MOSI Pin Muxing
  Select SerialIo SPI MOSI pin muxing. Refer to GPIO_*_MUXING_SERIALIO_SPIx_MOSI*
  for possible values.
**/
  UINT32                      PcdSerialIoSpiMosiPinMux;

/** Offset 0x00E0 - Serial Io I2C Device MMIO Base
  Assigns MMIO for Serial Io I2C controller usage in early stage.
**/
  UINT32                      PcdSerialIoI2cMmioBase;

/** Offset 0x00E4 - Serial Io I2C Sda Gpio Pin
  Select SerialIo I2C Rts pin. Refer to GPIO_*_MUXING_SERIALIO_I2C*_SDA* for possible values.
**/
  UINT32                      PcdSerialIoI2cSdaPin;

/** Offset 0x00E8 - Serial Io I2C Scl Gpio Pin
  Select SerialIo I2C Cts pin. Refer to GPIO_*_MUXING_SERIALIO_I2C*_SCL* for possible values.
**/
  UINT32                      PcdSerialIoI2cSclPin;

/** Offset 0x00EC - Serial Io I2C Gpio Pad termination
  0x0: Hardware default, 0x1: None, 0x13: 1kOhm weak pull-up, 0x15: 5kOhm weak pull-up,
  0x19: 20kOhm weak pull-up - Enable/disable SerialIo I2C0,I2C1,... pads termination
  respectively. One byte for each controller, byte0 for I2C0, byte1 for I2C1, and so on.
**/
  UINT8                       PcdSerialIoI2cPadsTerm;

/** Offset 0x00ED - Serial Io I2c Controller Number
  Select SerialIo I2C Controller number to be intilizaed during early boot. Default is 0xFF
  0:SerialIoI2c0, 1:SerialIoI2c1, 2:SerialIoI2c2, 0xFF:Disable
**/
  UINT8                       PcdSerialIoI2cNumber;

/** Offset 0x00EE - Enable Secondary Data Cache Region
  Enable Secondary Data Cache Region
  0:Disable, 1:Enable
**/
  UINT8                       EnableSecondaryDataCache;

/** Offset 0x00EF - Enable Signed FSP Code Cache Programming
  Enable Signed FSP Code Cache Programming
  0:Disable, 1:Enable
**/
  UINT8                       ProgramWriteBackCodeCache;

/** Offset 0x00F0
**/
  UINT8                       ReservedFsptUpd1[8];
} FSP_T_CONFIG;

/** Fsp T UPD Configuration
**/
typedef struct {

/** Offset 0x0000
**/
  FSP_UPD_HEADER              FspUpdHeader;

/** Offset 0x0020
**/
  FSPT_ARCH2_UPD              FsptArchUpd;

/** Offset 0x0040
**/
  FSPT_CORE_UPD               FsptCoreUpd;

/** Offset 0x0060
**/
  FSP_T_CONFIG                FsptConfig;

/** Offset 0x00F8
**/
  UINT8                       FsptUpdRsvd2[6];

/** Offset 0x00FE
**/
  UINT16                      UpdTerminator;
} FSPT_UPD;

#pragma pack()

#endif
