[package]
name = "modeltool"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"

[dependencies]
redox_intelflash = "0.1.3"
system76_ecflash = { git = "https://github.com/system76/ecflash", rev = "b08db293" }
